# Generated by Django 6.0.6 on 2026-06-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='csv_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
